title: glyphs.wf
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
google_analytics: UA-113492652-1
theme: 
collections:
  wf-partner:
    output: true
    permalink: /wf-partner/:name
github:
  is_project_page: false
  repository_url: https://github.com/pegasy/glyphs.wf
  repository_name: glyphs.wf
  owner_name: pegasy
  owner_url: https://github.com/pegasy/
